/**
 * Turns the SVGs in ./logotypes into index-marks.ts, a single-colour mark per
 * client, through the same normaliser the CMS path will use.
 *
 * Prototype scaffolding. When the archive reads from Sanity, this script goes
 * and the marks come from the logotype field on each project instead — but the
 * output shape stays the same, so nothing downstream changes.
 *
 *   node --import tsx src/components/home/build-index-marks.ts
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { normaliseLogotype } from "@/lib/logotype";

const dir = join(process.cwd(), "src/components/home/logotypes");
const out = join(process.cwd(), "src/components/home/index-marks.ts");

const marks = readdirSync(dir)
  .filter((f) => f.endsWith(".svg"))
  .sort()
  .map((file) => {
    const id = basename(file, ".svg");
    const mark = normaliseLogotype(readFileSync(join(dir, file), "utf8"));
    if (!mark) throw new Error(`${file} did not normalise into a usable mark`);
    return [id, mark] as const;
  });

const body = marks
  .map(([id, m]) => `  ${JSON.stringify(id)}: ${JSON.stringify(m)},`)
  .join("\n");

writeFileSync(
  out,
  `/**
 * Generated by build-index-marks.ts — do not edit by hand.
 *
 * One single-colour mark per client, stripped of every fill, class and style
 * block so it inherits the page's ink, and of everything that could execute.
 */
import type { Logotype } from "@/lib/logotype";

export const INDEX_MARKS: Record<string, Logotype> = {
${body}
};
`,
  "utf8"
);

console.log(`${marks.length} marks -> ${out}`);
for (const [id, m] of marks) console.log(`  ${id.padEnd(16)} ${m.viewBox.padEnd(22)} ${m.body.length} bytes`);
